version: "3.8"

services:

  database:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes: 
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
    - "6379:6379"
    volumes:
    - $PWD/redis-data:/var/lib/redis
    - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
    - REDIS_REPLICATION_MODE=master

  web:
    build: ./
    depends_on:
      - "database"
      - "redis"

    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4650
    ports:
      - 8080:8080
volumes:
  dbdata: